name: Stars

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Run the script
      - name: Run the script
        run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_STARS_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          branch: ${{ github.head_ref }}
          commit_message: Commit list
          commit_user_name: Analysis Tools Bot
          commit_user_email: bot@analysis-tools.dev
          commit_author: Analysis Tools Bot <bot@analysis-tools.dev>
